# Generated by Django 5.2.16 on 2026-08-01 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bios', '0002_initial'),
        ('competitions', '0001_initial'),
        ('places', '0002_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StadiumStanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ties', models.IntegerField(null=True)),
                ('shootout_wins', models.IntegerField(null=True)),
                ('shootout_losses', models.IntegerField(null=True)),
                ('goals_for', models.IntegerField(null=True)),
                ('goals_against', models.IntegerField(null=True)),
                ('stage', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.stadium')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ties', models.IntegerField(null=True)),
                ('shootout_wins', models.IntegerField(null=True)),
                ('shootout_losses', models.IntegerField(null=True)),
                ('goals_for', models.IntegerField(null=True)),
                ('goals_against', models.IntegerField(null=True)),
                ('stage', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('final', models.BooleanField(default=True)),
                ('date', models.DateField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('points_deducted', models.IntegerField(null=True)),
                ('deduction_reason', models.TextField()),
                ('position', models.IntegerField(null=True)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bios.bio')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.season')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ('season', 'competition', 'stage', 'group', '-points', '-wins', 'team'),
            },
        ),
    ]
