# Generated by Django 5.2.16 on 2026-08-01 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('short_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('founded', models.DateField(null=True)),
                ('dissolved', models.DateField(null=True)),
                ('real', models.BooleanField(default=True)),
                ('defunct', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('international', models.BooleanField(default=False)),
                ('affiliate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.city')),
            ],
            options={
                'ordering': ('short_name',),
            },
        ),
        migrations.CreateModel(
            name='TeamAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ('start',),
            },
        ),
    ]
