d = {
    'Alajuelense': '',
    'America': 'Club América',
    'Club America': 'Club América',
    'Arabe Unido': '',
    'Arnett Gardens': '',
    'Atlanta': '',
    'Austin': '',
    'Barcelona': 'FC Barcelona',
    'CP Baltimore': 'Crystal Palace Baltimore',
    'California': '',
    'Cape Cod Crusaders': '',
    'Carolina': '',
    'Central Coast': '',
    'Charleston': 'Charleston Battery',
    'Charlotte': '',
    'Chicago Sockers': '',
    'Chicago Stingers': '',
    'Cleveland': '',
    'Comunicaciones': 'C.S.D. Comunicaciones',
    'Connecticut': ,
    'Dep. Italchacao': ,
    'Des Moines Menace': ,
    'El Paso Patriots': ,
    'Fresno': ,
    'Guadalajara': 'Chivas',
    'Hampton Roads': '',
    'Harbour View': '',
    'Harrisburg': '',
    'Hershey': '',
    'Isidro Metapan': '',
    'Jacksonville': '',
    'LD Alajuelense': '',
    'Leon': '',
    'Long Island': '',
    'Luis Angel Firpo': '',
    'Marathon': '',
    'Miami': '',
    'Michigan': '',
    'Mid Michigan': '',
    'Mid-Michigan': '',
    'Millonarios': 'Millionarios', # Note this is wrong in my data.
    'Milwaukee': '',
    'Minnesota': '',
    'Monterrey': '',
    'Montreal': '',
    'Nashville Metros': '',
    'New Jersey': '',
    'New Orleans Riverboat Gamblers': '',
    'Ocean City Barons': ,
    'Olimpia': 'C.D. Olimpia',
    'Orange County Blue Star': '',
    'Orlando': '',
    'Pachucha': 'Pachuca',
    'Pittsburgh': '',
    'Portland': '',
    'Pumas': 'UNAM Pumas',
    'Puntarenas': '',
    'Real Espana': 'Real España',
    'Richmond': '',
    'Rochester': '',
    'Roma FC': 'Roma',
    'Saint Louis': '',
    'San Diego Gauchos': '',
    'San Francisco': '',
    'Sounders Select': '',
    'Sporting Cristal': '',
    'Stanislaus Utd': '',
    'Staten Island': '',
    'Syracuse': '',
    'Tauro': '',
    'Tennessee': '',
    'Texas Spurs': '',
    'Tigres UANL': 'UANL Tigres',
    'U.Catolica': '',
    'United Petrotrin': '',
    'Uruguay SC': '',
    'Vancouver': '',
    'Virginia Beach': '',
    'Western Mass': '',
    'Wilmington': '',
    'Worcester Kings': ',
    }
