# Generated by Django 5.2.16 on 2026-08-01 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bios', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('abbreviation', models.CharField(max_length=5)),
                ('joined', models.DateField(null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StatePopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('population', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('code', models.CharField(max_length=15)),
                ('subconfederation', models.CharField(max_length=15)),
                ('confederation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.confederation')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.country')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('short_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('opened', models.DateField(null=True)),
                ('year_opened', models.IntegerField(null=True)),
                ('closed', models.DateField(null=True)),
                ('year_closed', models.IntegerField(null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('width', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('measure', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=31, null=True)),
                ('denomination', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('architect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bios.bio')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.city')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StadiumMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.stadium')),
            ],
        ),
    ]
