# Generated by Django 5.2.16 on 2026-09-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
