# Generated by Django 5.2.16 on 2026-09-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0002_initial'),
        ('news', '0002_feeditem_archive_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='people',
            field=models.ManyToManyField(related_name='news', to='bios.bio'),
        ),
    ]
