# Generated by Django 5.2.16 on 2026-08-01 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bios', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bios.bio')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minute', models.IntegerField(null=True)),
                ('penalty', models.BooleanField(default=False)),
                ('own_goal', models.BooleanField(default=False)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('own_goal_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_goal_set', to='bios.bio')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bios.bio')),
            ],
            options={
                'ordering': ('game', 'minute', 'team'),
            },
        ),
    ]
