from django.test import SimpleTestCase

from competitions import territory
from competitions.territory import (COLORS, MAIN, NORTH, assign, atlas, distance_km,
                                    frame_of, place_labels, season_map, territories)


def club(name, lat, lon, slug=None):
    return {'name': name, 'slug': slug or name.lower().replace(' ', '-'), 'lat': lat, 'lon': lon}


DALLAS = club('FC Dallas', 32.7767, -96.7970, 'fc-dallas')
HOUSTON = club('Houston Dynamo', 29.7604, -95.3698, 'houston-dynamo')
GALAXY = club('LA Galaxy', 34.0522, -118.2437, 'la-galaxy')
CHIVAS = club('Chivas USA', 34.0522, -118.2437, 'chivas-usa')
TORONTO = club('Toronto FC', 43.6532, -79.3832, 'toronto-fc')


class CountyAtlasTests(SimpleTestCase):
    """
    places/counties.json is generated by tools/county_map.py; these are the
    properties the map depends on, not the file's contents.
    """

    def test_holds_the_counties_and_the_census_divisions(self):
        units = atlas()
        us = [u for u in units.values() if u['country'] == 'US']
        ca = [u for u in units.values() if u['country'] == 'CA']

        # 3,143 counties and equivalents in 2020, once Puerto Rico and the
        # island territories are set aside; 293 census divisions in 2021.
        assert len(us) == 3143
        assert len(ca) == 293
        assert len({u['state'] for u in us}) == 51  # fifty states and DC
        assert len({u['state'] for u in ca}) == 13  # ten provinces, three territories

    def test_leaves_out_puerto_rico(self):
        assert not any(u['state'] == 'PR' for u in atlas().values())

    def test_every_centroid_sits_inside_its_own_outline(self):
        for uid, unit in atlas().items():
            lons = [p[0] for ring in unit['rings'] for p in ring]
            lats = [p[1] for ring in unit['rings'] for p in ring]
            assert min(lons) <= unit['lon'] <= max(lons), uid
            assert min(lats) <= unit['lat'] <= max(lats), uid

    def test_the_far_north_is_kept_but_not_drawn(self):
        units = atlas()
        north = [u for u in units.values() if u['lat'] > NORTH]

        assert north, 'the territories are missing'
        # Alaska is north of 60 too, but it has an inset of its own.
        assert {u['state'] for u in north} == {'AK', 'YT', 'NT', 'NU'}
        assert all(frame_of(u) is None for u in north if u['state'] != 'AK')
        assert frame_of(units['48113']) == 'main'  # Dallas County
        assert frame_of(units['02020']) == 'alaska'  # Anchorage
        assert frame_of(units['15003']) == 'hawaii'  # Honolulu

    def test_western_canada_lands_west(self):
        # The Statistics Canada file is in a Lambert projection; a sign slip
        # in the inverse once mirrored British Columbia onto Quebec.
        units = atlas()
        assert -124 < units['CA5915']['lon'] < -122  # Greater Vancouver
        assert -80 < units['CA3520']['lon'] < -79  # Toronto


class AssignmentTests(SimpleTestCase):
    def test_great_circle_distance(self):
        # Dallas to Houston is about 360 km as the crow flies.
        assert 350 < distance_km(32.7767, -96.7970, 29.7604, -95.3698) < 370
        assert distance_km(40, -100, 40, -100) == 0

    def test_each_unit_goes_to_the_nearest_club(self):
        units = {
            'dallas': {'lat': 32.77, 'lon': -96.78},
            'harris': {'lat': 29.86, 'lon': -95.39},
            'travis': {'lat': 30.33, 'lon': -97.78},  # Austin: nearer Houston than Dallas
        }
        terrs = territories([DALLAS, HOUSTON])
        by_name = {t['index']: t['name'] for t in terrs}
        assigned = {uid: by_name[i] for uid, i in assign(units, terrs).items()}

        assert assigned == {'dallas': 'FC Dallas', 'harris': 'Houston Dynamo',
                            'travis': 'Houston Dynamo'}

    def test_clubs_sharing_a_city_share_a_striped_territory(self):
        terrs = territories([GALAXY, DALLAS, CHIVAS])

        assert [t['name'] for t in terrs] == ['Chivas USA / LA Galaxy', 'FC Dallas']
        la = terrs[0]
        assert la['colors'] == [COLORS['chivas-usa'], COLORS['la-galaxy']]
        assert [c['name'] for c in la['clubs']] == ['Chivas USA', 'LA Galaxy']

    def test_unknown_club_gets_the_neutral_grey(self):
        terrs = territories([club('Rochester Rhinos', 43.16, -77.61)])
        assert terrs[0]['color'] == territory.UNASSIGNED


class ProjectionTests(SimpleTestCase):
    def test_albers_keeps_east_and_west_apart_and_north_up(self):
        seattle = MAIN(-122.33, 47.61)
        miami = MAIN(-80.19, 25.76)
        toronto = MAIN(-79.38, 43.65)

        assert seattle[0] < toronto[0]
        assert miami[0] > seattle[0]
        assert seattle[1] > miami[1]
        assert toronto[1] > miami[1]

    def test_labels_stay_in_the_frame_and_off_each_other(self):
        marks = [
            {'name': 'New York Red Bulls', 'total': 50, 'label': {'x': 700, 'y': 300}},
            {'name': 'New York City FC', 'total': 5, 'label': {'x': 704, 'y': 305}},
            {'name': 'San Jose Earthquakes', 'total': 60, 'label': {'x': 10, 'y': 400}},
            {'name': 'Unlabelled', 'total': 1},
        ]
        place_labels(marks, 960)

        assert marks[1]['label']['y'] - marks[0]['label']['y'] >= territory.LABEL_HEIGHT
        assert marks[2]['label']['x'] > len('San Jose Earthquakes') * territory.LABEL_GLYPH / 2
        assert 'label' not in marks[3]


class SeasonMapTests(SimpleTestCase):
    def test_no_clubs_no_map(self):
        assert season_map([]) is None

    def test_two_clubs_split_the_continent(self):
        result = season_map([DALLAS, TORONTO])
        marks = {m['name']: m for m in result['marks']}

        assert set(marks) == {'FC Dallas', 'Toronto FC'}
        assert marks['FC Dallas']['total'] + marks['Toronto FC']['total'] == result['units']
        assert marks['Toronto FC']['ca'] > marks['FC Dallas']['ca']
        assert marks['FC Dallas']['us'] > marks['Toronto FC']['us']
        assert result['north'] == sum(m['north'] for m in result['marks'])
        assert abs(sum(m['share'] for m in result['marks']) - 100) < 0.01

        # One path per territory, drawn as many subpaths.
        assert marks['FC Dallas']['d'].startswith('M')
        assert marks['FC Dallas']['d'].count('Z') > 1000
        assert marks['FC Dallas']['fill'] == COLORS['fc-dallas']
        assert result['svg']['width'] == territory.WIDTH
        assert result['svg']['height'] < territory.WIDTH

    def test_shared_city_draws_a_stripe_pattern(self):
        result = season_map([GALAXY, CHIVAS, DALLAS])
        la = [m for m in result['marks'] if m['name'] == 'Chivas USA / LA Galaxy'][0]

        assert la['fill'] == 'url(#stripe-%d)' % la['index']
        assert result['stripes'] == [la]


class PaletteTests(SimpleTestCase):
    def test_every_club_the_league_has_had_is_colored(self):
        for slug in ('tampa-bay-mutiny', 'miami-fusion', 'chivas-usa', 'san-diego-fc',
                     'sporting-kansas-city', 'minnesota-united-fc'):
            assert slug in COLORS, slug

    def test_colors_are_hex_and_distinct(self):
        assert all(len(c) == 7 and c.startswith('#') for c in COLORS.values())
        assert len(set(COLORS.values())) == len(COLORS)
