from django.test import SimpleTestCase

from competitions.templatetags.charts import band, country_map, normalize_country, world


def row(name, share, country=True):
    return {'name': name, 'value': int(share * 10000), 'share': share,
            'country': object() if country else None}


class WorldAtlasTests(SimpleTestCase):
    """
    places/world.json is generated by tools/world_map.py; these are the
    properties the map depends on, not the file's contents.
    """

    def test_football_countries_resolve_to_outlines(self):
        atlas = world()

        for name in ['United States', 'England', 'Scotland', 'Wales',
                     'Saint Kitts and Nevis', 'Jamaica', 'Zaire']:
            codes = atlas['names'][normalize_country(name)]
            assert codes, name
            assert all(code in atlas['shapes'] for code in codes), name

    def test_the_united_states_keeps_alaska_and_hawaii(self):
        assert len(world()['names'][normalize_country('United States')]) == 3

    def test_the_home_nations_stay_apart(self):
        atlas = world()
        codes = {name: atlas['names'][normalize_country(name)]
                 for name in ('England', 'Scotland', 'Wales', 'Northern Ireland')}

        assert sorted(sum(codes.values(), [])) == ['ENG', 'NIR', 'SCT', 'WLS']

    def test_overseas_departements_are_their_own_countries(self):
        atlas = world()

        assert atlas['names'][normalize_country('Martinique')] == ['MTQ']
        assert 'MTQ' not in atlas['names'][normalize_country('France')]


class BandTests(SimpleTestCase):

    def test_bands_run_darkest_first(self):
        assert band(0.60) == 1
        assert band(0.25) == 1
        assert band(0.10) == 2
        assert band(0.05) == 3
        assert band(0.02) == 4
        assert band(0.001) == 5


class CountryMapTests(SimpleTestCase):

    def test_shades_what_it_is_given(self):
        context = country_map([row('Jamaica', 0.6), row('Ireland', 0.4)], 'caption')

        assert context['svg']
        assert len(context['marks']) == 2
        assert {m['band'] for m in context['marks']} == {1}

    def test_a_country_too_small_to_draw_becomes_a_dot(self):
        """Saint Kitts is a fifth of a degree wide and can be a tenth of a season."""
        context = country_map([row('United States', 0.9),
                               row('Saint Kitts and Nevis', 0.1)], 'caption')
        dots = [m for m in context['marks'] if 'dot' in m]

        assert [m['title'].split(':')[0] for m in dots] == ['Saint Kitts and Nevis']

    def test_the_crop_follows_the_main_landmass(self):
        """Alaska and the Aleutians would otherwise crop the map to the world."""
        wide = country_map([row('United States', 1.0)], 'caption')['svg']

        assert wide['width'] / wide['height'] < 3

    def test_unrecorded_minutes_are_not_a_missing_outline(self):
        context = country_map([row('Jamaica', 0.8),
                               row('not recorded', 0.2, country=False)], 'caption')

        assert context['unmapped'] == []

    def test_the_noun_follows_the_measure(self):
        context = country_map([row('Jamaica', 1.0)], 'caption', 'games')

        assert context['marks'][0]['title'] == 'Jamaica: 10,000 games, 100.0%'

    def test_a_single_appearance_reads_as_one(self):
        context = country_map([{'name': 'Croatia', 'value': 1, 'share': 1.0,
                                'country': object()}], 'caption', 'games')

        assert context['marks'][0]['title'] == 'Croatia: 1 game, 100.0%'

    def test_nothing_to_draw(self):
        assert country_map([row('not recorded', 1.0, country=False)], 'c')['svg'] is None
