# Generated by Django 5.2.16 on 2026-08-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confederation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=150)),
                ('region', models.CharField(max_length=255)),
                ('founded', models.DateField(null=True)),
            ],
        ),
    ]
