# Generated by Django 5.2.16 on 2026-08-01 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bios', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttype', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bios.bio')),
                ('team_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from', to='teams.team')),
                ('team_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to', to='teams.team')),
            ],
        ),
    ]
