# Generated by Django 5.2.16 on 2026-08-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, unique=True)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
    ]
