# Generated by Django 5.2.16 on 2026-09-20 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0002_initial'),
        ('places', '0003_city_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='national_set', to='places.country'),
        ),
    ]
