# Generated by Django 5.2.16 on 2026-08-01 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=15)),
                ('slug', models.SlugField(max_length=150)),
                ('international', models.BooleanField(default=False)),
                ('ctype', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('scope', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SuperSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('order', models.IntegerField()),
                ('order2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after', to='competitions.competition')),
                ('before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before', to='competitions.competition')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='relationships',
            field=models.ManyToManyField(through='competitions.CompetitionRelationship', to='competitions.competition'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('order', models.IntegerField(blank=True, null=True)),
                ('order2', models.IntegerField(blank=True, null=True)),
                ('competition_original_name', models.CharField(max_length=255)),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('minutes_with_age', models.IntegerField(blank=True, null=True)),
                ('age_minutes', models.FloatField(blank=True, null=True)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('super_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.superseason')),
            ],
            options={
                'ordering': ('order', 'super_season__order2', 'competition'),
            },
        ),
    ]
