# Generated by Django 5.2.16 on 2026-09-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
