# Generated by Django 5.2.16 on 2026-08-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=255)),
                ('round', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('stage', models.CharField(max_length=255)),
                ('starter_count', models.IntegerField(blank=True, null=True)),
                ('goal_count', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('has_date', models.BooleanField()),
                ('team1_original_name', models.CharField(max_length=255)),
                ('team2_original_name', models.CharField(max_length=255)),
                ('team1_score', models.IntegerField(null=True)),
                ('official_team1_score', models.IntegerField(null=True)),
                ('team2_score', models.IntegerField(null=True)),
                ('official_team2_score', models.IntegerField(null=True)),
                ('team1_result', models.CharField(max_length=5)),
                ('team2_result', models.CharField(max_length=5)),
                ('result_unknown', models.BooleanField(default=False)),
                ('not_played', models.BooleanField(default=False)),
                ('forfeit', models.BooleanField(default=False)),
                ('goals', models.IntegerField()),
                ('minigame', models.BooleanField(default=False)),
                ('indoor', models.BooleanField(default=False)),
                ('minutes', models.IntegerField(default=90)),
                ('neutral', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
                ('video', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('merges', models.IntegerField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='GameMinute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('team1_score', models.IntegerField()),
                ('team2_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(max_length=1023)),
            ],
        ),
    ]
