# Generated by Django 5.2.16 on 2026-08-01 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bios', '0002_initial'),
        ('competitions', '0001_initial'),
        ('games', '0001_initial'),
        ('places', '0001_initial'),
        ('sources', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.city'),
        ),
        migrations.AddField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='game',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.country'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='teams.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='linesman1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linesman1_games', to='bios.bio'),
        ),
        migrations.AddField(
            model_name='game',
            name='linesman2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linesman2_games', to='bios.bio'),
        ),
        migrations.AddField(
            model_name='game',
            name='linesman3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linesman3_games', to='bios.bio'),
        ),
        migrations.AddField(
            model_name='game',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_refereed', to='bios.bio'),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.season'),
        ),
        migrations.AddField(
            model_name='game',
            name='shootout_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='something', to='teams.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.stadium'),
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t1_games', to='teams.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t2_games', to='teams.team'),
        ),
        migrations.AddField(
            model_name='gameminute',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
        migrations.AddField(
            model_name='gamesource',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
        migrations.AddField(
            model_name='gamesource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.source'),
        ),
        migrations.AddField(
            model_name='game',
            name='sources',
            field=models.ManyToManyField(through='games.GameSource', to='sources.source'),
        ),
    ]
