# Generated by Django 5.2.16 on 2026-08-01 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
            ],
            options={
                'ordering': ('competition', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AwardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.award')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.season')),
            ],
            options={
                'ordering': ('year', 'season'),
            },
        ),
    ]
